---
apiVersion: v1
kind: Service
metadata:
  name: homebridge 
spec:
  type: NodePort 
  selector:
    app: homebridge 
  ports:
  - name: homebridge
    port: 51827
    protocol: TCP
    targetPort: homebridge
  - name: homebridge-2
    port: 5353
    protocol: TCP
    targetPort: homebridge-2
  - name: http 
    port: 8581
    protocol: TCP
    targetPort: 8581 
  externalIPs:
  - 192.168.0.211
  - 192.168.0.221
  - 192.168.0.222 
  - 192.168.0.223
